### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by Korngut** [Korngut/PiTV#4]
When we tried to set the background color to completely white, we encountered a problem and the background did not change.
We used the command `.setBackground` and `.setForgeground`
At the end, we deleted the command, but if we define a Gif that is smaller than 1920*1080, it will not look good.
When we tried to use Chatgpt, she offered to make the switch between the .`setForgeground` and .`setBackground,` and it didn't work here either.

`Error `did not appear

**Comment by I-No-oNe** [comment]
@Korngut please check my branch, and @Keller6738  code

**Comment by I-No-oNe** [comment]
> ## I FIxed it in #6
